---
title: "HW 01"
author: "Jiayue He"
format: 
  html:
    embed-resources: true
toc: true
---

## 0 - Setup

```{r} 

if (!require("pacman")) 
  install.packages("pacman")

# use this line for installing/loading
#pacman::p_load() 

devtools::install_github("tidyverse/dsbox")
```

## 1 - Road traffic accidents in Edinburgh

1) get basic dataset: 
```{r label-me-1}
#inspect the document
??accidents
library(ggplot2)
library(dplyr)
install.packages("patchwork")
library(patchwork)
accident<-dsbox::accidents
accident
```
2) start plot_weekdays 
```{r}

#find color website: https://imagecolorpicker.com/en

#weekday_accident <- accident %>% filter(day_of_week %in% c('Monday', 'Tuesday','Wednesday','Thursday','Friday'))

weekday_accident <- accident %>% filter(day_of_week != c('Saturday', 'Sunday'))
weekday_accident

weekday_plot<-ggplot(weekday_accident, aes(x = time, fill = severity)) +
  geom_density(alpha = 0.8) +
  scale_fill_manual(values = c("Fatal" = "#a993b0", "Serious" = "#9ec9c7", "Slight" = "#fef39f"))+ xlab("weekday") +
  ggtitle("weekday")

weekday_plot


```
3) another plot_weekend
```{r}


weekend_accident <- accident %>% filter(day_of_week %in% c('Saturday', 'Sunday'))
weekend_accident


weekend_plot<-ggplot(weekend_accident, aes(x = time, fill = severity)) +
  geom_density(alpha = 0.8) +
  scale_y_continuous(breaks = c(0, 1e-05, 2e-05)) +
  scale_fill_manual(values = c("Fatal" = "#a993b0", "Serious" = "#9ec9c7", "Slight" = "#fef39f"))+ xlab("Time of day")+
  ggtitle("weekend")

weekend_plot

```
4) integrate the plot 
```{r}

```

## 2 - NYC marathon winners

```{r label-me-2}

```

## 3 - US counties


## 4 - Rental apartments in SF


## 5 - Napoleon’s march.
